'use strict';

let Constants = {
	BasePath: TagprintsSmugmugData.BasePath,
	AjaxUrl: TagprintsSmugmugData.AjaxUrl
};

export default Constants;

export const GALLERY_LIST_RECEIVED = 'GALLERY_LIST_RECEIVED';
export const GALLERY_LIST_THUMBNAIL_RECEIVED = 'GALLERY_LIST_THUMBNAIL_RECEIVED';
export const GALLERY_LIST_LOAD = 'GALLERY_LIST_LOAD';
export const GALLERY_LOAD = 'GALLERY_LOAD';
export const GALLERY_SEARCH_RECEIVED = 'GALLERY_SEARCH_RECEIVED';
export const GALLERY_SEARCH_NOT_FOUND = 'GALLERY_SEARCH_NOT_FOUND';
export const GALLERY_IMAGES_RECEIVED = 'GALLERY_IMAGES_RECEIVED';
export const GALLERY_INIT = 'GALLERY_INIT';
export const GALLERY_LIST_INIT = 'GALLERY_LIST_INIT';
export const GALLERY_SHOW_UNLOCK = 'GALLERY_SHOW_UNLOCK';
export const GALLERY_INVALID_UNLOCK = 'GALLERY_INVALID_UNLOCK';
export const GALLERY_UNLOCKED = 'GALLERY_UNLOCKED';
export const FOLDER_LIST_LOAD = 'FOLDER_LIST_LOAD';
export const FOLDER_LIST_RECEIVED = 'FOLDER_LIST_RECEIVED';
export const FOLDER_LIST_THUMBNAIL_RECEIVED = 'FOLDER_LIST_THUMBNAIL_RECEIVED';
export const FOLDER_LIST_INIT = 'FOLDER_LIST_INIT';
